version: '3'

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env

  app:
    build: .
    container_name: app
    tty: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_container

volumes:
  mongodb_data_container:
