name: Docker Publish Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push the Image
        run: |
          docker login --username glaucia86 --password ${{ secrets.GH_PACKAGE_PERSONAL_TOKEN }} $REGISTRY
          docker build . --tag $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
