name: Create and Publish a Docker Image to GHCR image/package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Use docker.io for DockerHub if empty
  REGISTRY: ghcr.io

  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_PERSONAL_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . --tag ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
          docker run ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
          docker push ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
