name: Create and Publish a Docker Image to GHCR image/package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Use docker.io for DockerHub if empty
  REGISTRY: ghcr.io

  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and Push Docker Image
        run: |
          docker login --username glaucia86 --password ${{ secrets.GH_PACKAGE_PERSONAL_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
          docker run ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
          docker push ghcr.io/glaucia86/api-rest-ts-aks-ghcr:latest
