name: Create and Publish a Docker Image to GHCR image/package

on:
  workflow_dispatch:
    push:
      branches:
        - main
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Call Docker Publish Workflow
        uses: .github/workflows/docker-publish-workflow.yaml
